services:
  dev:
    build: .
    volumes:
      - .:/app
      - /media/cconstantine/RPI-RP2:/mnt/pico_drive
      - "/dev/bus/usb:/dev/bus/usb"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    working_dir: /app
    # Keep container running
    stdin_open: true
    tty: true
    command: /bin/bash
    environment:
      - WIFI_SSID
      - WIFI_PASSWORD
